"""Permission vocabulary, profiles and approval handling."""

from __future__ import annotations

from agentbetta.permissions.approvals import (
    HIGH_RISK,
    RISK_ORDER,
    ApprovalDecision,
    ApprovalRequest,
    ApprovalService,
)
from agentbetta.permissions.policy import (
    ALL_PERMISSIONS,
    BROWSER_DOWNLOAD,
    BROWSER_INTERACT,
    BROWSER_READ,
    DESKTOP_CONTROL,
    DESKTOP_READ,
    FILE_DELETE,
    FILE_READ,
    FILE_WRITE,
    MEMORY_READ,
    MEMORY_WRITE,
    NETWORK_HTTP,
    NETWORK_SHARE,
    PROCESS_LAUNCH,
    SHELL_EXEC,
    TOOLS_FOR_PERMISSION,
)
from agentbetta.permissions.profiles import (
    DEFAULT_PROFILE_KEY,
    PROFILES,
    PROFILE_EXTENDED,
    PROFILE_FULL,
    PROFILE_SAFE,
    PROFILE_STANDARD,
    PermissionProfile,
    get_profile,
    inspect_profiles,
    profile_permission_set,
)

__all__ = [
    "ALL_PERMISSIONS",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalService",
    "BROWSER_DOWNLOAD",
    "BROWSER_INTERACT",
    "BROWSER_READ",
    "DEFAULT_PROFILE_KEY",
    "DESKTOP_CONTROL",
    "DESKTOP_READ",
    "FILE_DELETE",
    "FILE_READ",
    "FILE_WRITE",
    "HIGH_RISK",
    "MEMORY_READ",
    "MEMORY_WRITE",
    "NETWORK_HTTP",
    "NETWORK_SHARE",
    "PROCESS_LAUNCH",
    "PROFILES",
    "PROFILE_EXTENDED",
    "PROFILE_FULL",
    "PROFILE_SAFE",
    "PROFILE_STANDARD",
    "PermissionProfile",
    "RISK_ORDER",
    "SHELL_EXEC",
    "TOOLS_FOR_PERMISSION",
    "get_profile",
    "inspect_profiles",
    "profile_permission_set",
]
